// This file is auto-generated by Claude AI

#define UNIT_TESTS
#define LCD_DEBUG  // Enable LCD debug features for testing

#include "unity.h"
#include <stdint.h>

// mocking avr vars to compile
uint8_t mockPort = 0;
uint16_t mockOcr = 0;
#define PORTA mockPort
#define PORTF mockPort
#define DDRA mockPort
#define DDRF mockPort
#define PINF0 1
#define PINF1 1
#define OCR5A mockOcr

#include <stdbool.h>
#include <string.h>
#include "../../src/common/globalVars.h"
#include "../../src/display/messageProcessor.c"
#include "../../src/scheduler/schedulerFunctionsCircBuf.c"
#include "../../src/display/lcdProcessor.c"

uint8_t currentPcConnected;
uint8_t nextErrorPrintLine;
bool errorInLine[2];
bool tick32ms;
enum PcStateEnum pcState[NUM_OF_UARTS];
bool isJigglerOn[NUM_OF_UARTS];
uint8_t currentPcConnected;
uint8_t previousPcConnected;
char* kbPcStateMessage;

void setUp(void) 
{
    // Reset message processor state
    nextErrorPrintLine = 1;
    errorInLine[0] = false;
    errorInLine[1] = false;
    tick32ms = false;
    
    // Reset PC states
    for (int i = 0; i < NUM_OF_UARTS; i++) {
        pcState[i] = PcOff;
        isJigglerOn[i] = false;
    }
    currentPcConnected = 0;
    previousPcConnected = 0;
}

void tearDown(void) {}

void test_convertSemiByte2Char_numbers(void)
{
    TEST_ASSERT_EQUAL_CHAR('0', convertSemiByte2Char(0));
    TEST_ASSERT_EQUAL_CHAR('5', convertSemiByte2Char(5));
    TEST_ASSERT_EQUAL_CHAR('9', convertSemiByte2Char(9));
}

void test_convertSemiByte2Char_hexLetters(void)
{
    TEST_ASSERT_EQUAL_CHAR('A', convertSemiByte2Char(10));
    TEST_ASSERT_EQUAL_CHAR('C', convertSemiByte2Char(12));
    TEST_ASSERT_EQUAL_CHAR('F', convertSemiByte2Char(15));
}
